[icons]
telegram = "îˆ—"
firefox = "ï‰©"
Alacritty = "ï„ "
#Termite = "ï„ "
gpick = "ó°´±"
#Nautilus = "ğŸ“˜"
# smile emoji
#MyNiceProgram = "ğŸ˜›"
nemo = "ï¼"
xfceterm = "ï’‰"
chrome = "ï‰¨"
code = "ó°¨"
subl = "îš–"
rustdesk = "ï„ˆ"
anydesk = "ï’©"
brave = "ó°‡§"
virtm = "ï‚…"
discord = "ó°™¯"
calc = "ï“·"
gimp = "ï‡…"
steam = "ï†¶"
thunderbird = "ï¯"
zathura = "ï‡"
stfloat = "î•"
notify = "ïª"
themes = "îˆ«"
keepass = "ï‚„"
gdisk = "ï‘³"
calculator = "ó°ƒ¬"
obsidian = "ï’Š"
draw = "ó±¦¹"
ssh = "ó°£€"
qt5ct = "îˆ«"
rpimg = "îœ¢"
mpv = "ï€"
nvr = "ï€½"
nvim = "î˜«"
fontm = "ïŠ€"
fileroller = "ïƒ‡"
feh = "ï€¾"
bluetooth= "ïŠ”"
protonvpn= "ï©"

#[aliases.instance]
#"realmonitor" = "nvr"
#"ssh" = "ssh"
#"nvim" = "nvim"

[aliases.class]
"TelegramDesktop" = "telegram"
"Org\\.gnome\\.Nautilus" = "nautilus"
"libreoffice-calc" = "calc"
"libreoffice-draw" = "draw"
"Firefox" = "firefox"
"Google-chrome-unstable" = "chrome-dev"
"Google-chrome" = "chrome"
"Gimp-\\d\\.\\d\\d" = "gimp"
"^discord$" = "discord"
"Steam" = "steam"
"Thunderbird" = "thunderbird"
"Xfce4-terminal" = "xfceterm"
"Nemo" = "nemo"
"Brave-browser" = "brave"
"Virt-manager" = "virtm"
"org\\.pwmt\\.zathura" = "zathura"
"Zathura" = "zathura"
"St" = "stfloat"
#"drawn-st" = "stfloat"
"Subl" = "subl"
"code-oss" = "code"
"Xfce4-notifyd" = "notify"
"Rustdesk" = "rustdesk"
"Anydesk" = "anydesk"
"Lxappearance" = "themes"
"KeePassXC" = "keepass"
"Gnome-disks" = "gdisk"
"Mate-calc" = "calculator"
"obsidian" = "obsidian"
"qt5ct" = "qt5ct"
"Imager" = "rpimg"
"mpv" = "mpv"
"Font-manager" = "fontm"
"File-roller" = "fileroller"
"feh" = "feh"
"blueman-manager" = "bluetooth"
"Alacritty" = "Alacritty"
"Protonvpn" = "protonvpn"

[general]
#separator = " î‚± "
#default_icon = "ï„‘"
default_icon = "ğŸ’€"
separator = "Â·"
wm_property = "class"

[options]
remove_duplicates = false
no_names = true
no_icon_names = false
